apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HelloHarness
  description: A description of your service
  tags:
    - java
    - spring
spec:
  type: service
  lifecycle: production
  owner: iamlennym
