# Get the version.
version=`git describe --tags --long --always`

# Get the build date and time
build_time=`date '+%Y-%m-%d_%H-%M'`

# Write out the package.
cat << EOF > releases/version.go
//	Generated by ./genVersion.sh

package releases

var (
	VersionNumber = "$version"
	BuildTime = "$build_time"
)
EOF
