apiVersion: v1
kind: Service
metadata:
  name: hello-harness-lb
  namespace: harness-demo
spec:
  ports:
    - name: hello-harness-port
      port: 80
      targetPort: 12345
  selector:
    app: hello-harness
  type: LoadBalancer
